[project]
name = "pbd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.11"
dependencies = [
    "boto3>=1.7.84",
    "botocore>=1.10.84",
    "github>=1.2.7",
    "kubernetes>=32.0.1",
    "s3fs>=0.2.0",
    "zenml==0.80.0",
]
