pipeline:
  name: ocr_pipeline
  enable_cache: false
  settings:
    docker:
      parent_image: "ghcr.io/atharva-phatak/pbd-data_extraction:latest"
      skip_build: true
    kubernetes_orchestrator:
      pod_settings:
        resources:
          requests:
            cpu: "4"
            memory: "3Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "6"
            memory: "4Gi"
            nvidia.com/gpu: "1"
        env_from:
          - secretRef:
              name: "aws-credentials"
        labels:
          app: "ocr-pipeline"
          component: "step"
      orchestrator_pod_settings:
        resources:
          requests:
            cpu: "2"
            memory: "70Mi"
          limits:
            cpu: "4"
            memory: "256Mi"
        env_from:
          - secretRef:
              name: "aws-credentials"
        labels:
          app: "zenml-orchestrator"
          component: "orchestrator"

  steps:
    download_from_minio:
      parameters:
        endpoint: "fsml.minio.info"
        bucket: "images-bucket"
        object_key: "ocr/test.zip"
        local_path: "/tmp/images.zip"

    extract_zip:
      parameters:
        extract_to: "/tmp/images"

    ocr_images:
      image_dir: "/tmp/images"
      model_path: "/models/"
      max_new_tokens: 4096
      min_pixels: 512
      max_pixels: 512