name: Build mistral.rs image

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight UTC
  push:
    branches: [main]
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile.python-app'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout EricLBuehler/mistral.rs repository
        uses: actions/checkout@v4
        with:
          repository: EricLBuehler/mistral.rs
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Lowercase Repository Owner
        id: repo-owner
        run: |
          echo "repo_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push mistral.rs base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cuda.all
          push: true
          tags: ghcr.io/${{ steps.repo-owner.outputs.repo_owner }}/mistralrs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
