name: ARC Test

on:
  workflow_dispatch:

jobs:
  test:
    # This must exactly match your runner scale set name
    runs-on: pbd-runner-scale-set

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print environment info
        run: |
          echo "✅ Hello from ARC!"
          uname -a
          whoami
          docker --version || echo "🐳 Docker not installed"
